### ISSUE TITLE
Add `curie_map` to the mapping_sets listed in the registry.yml

### ISSUE THREAD

**Issue by anitacaron** [monarch-initiative/monarch-mapping-commons#30]
A lot of new prefixes in the `gene_mappings.sssom.tsv`.
This is needed for #29

**Comment by glass-ships** [comment]
can you provide some more details on its? 
(ie. 
- should this be a new field underneath each mapping set within the registry? 
- what would the value of the `curie_map` key be? 
)

**Comment by matentzn** [comment]
@glass-ships just so we avoid more issues in the future, would you mind working through (or at least reading through) https://mapping-commons.github.io/sssom/tutorial/, and pay special attention to mapping set metadata? The values in curie_map are all the prefix expansions needed to go between a prefix like MONDO or UMLS to its respective URI expansion.

**Comment by matentzn** [comment]
(we should really have mapping set validation)

**Comment by glass-ships** [comment]
thanks nico

though that doesn't totally resolve my question regarding the specifics of what's needed here (especially considering the gene mappings aren't generated here and don't have a resolving w3id url) 
but i can maybe work with @kevinschaper at some point to figure out the details

**Comment by matentzn** [comment]
@anitacaron just to move things along more quickly can you help Glass please?

The goal is that all SSSOM files in this mapping commons are valid according to SSSOM validate (SSSOM toolkit)

**Comment by glass-ships** [comment]
after skimming the tsv file itself, i have 
```
    curie_map:
      ENSEMBL: something
      FB: something
      HGNC: something
      MGI: something
      NCBIGene:  something
      RGD: something
      UniProtKB: something
      WB: something
      Xenbase: something
      ZFIN: something
```

but as for what to replace "something" with, i'm not sure. 
i also don't see anything in the sssom docs about validate, is there anything else needed to see that it's "valid"?
